---
- name: Installation of docker
  hosts: mysql
  user: root

  tasks:

  - name: install epel-release
    command: amazon-linux-extras install epel -y

  - name: install docker
    command: yum install docker -y

  - name: Restart docker
    service:
      name: docker
      state: restarted

  - name: Launching Mysql container
    command: docker run -d --name mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=root@1234 -v /var/lib/mysql:/var/lib/mysql mysql:latest


